optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'train', npoints: 2048}},
  val : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 2048}},
  test : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 2048}}}

model : {
  NAME: PCP_MAE,
  group_size: 32,
  num_group: 64,
  loss: cdl2,
  
  # parameters for predicting the centers
  pred_loss: l2, # l2 by default | l2, sml1, cos, l1
  ita: 0.1,  # 0.1 by default
  pred_pos_transformer_layer: 0,  # 0 by default
  add_detach: True,  # True by default 
  
  transformer_config: {
    mask_ratio: 0.6,  
    mask_type: 'rand',
    trans_dim: 384,
    encoder_dims: 384,
    depth: 12,
    drop_path_rate: 0.1,
    num_heads: 6,
    decoder_depth: 4,
    decoder_num_heads: 6,
  },

  clip_config: {
    visual_encoder: 'ViT-B/16',
    feat_dim: 9984
  },
  }

npoints: 2048
total_bs : 128
step_per_update : 1
max_epoch : 300